--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11.06.2026 13:31:52
-- Server version: 10.3.39
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE testao1145;

--
-- Drop table `testcrossquestion`
--
DROP TABLE IF EXISTS testcrossquestion;

--
-- Drop table `studentanswer`
--
DROP TABLE IF EXISTS studentanswer;

--
-- Drop table `mark`
--
DROP TABLE IF EXISTS mark;

--
-- Drop table `teachercrosssubject`
--
DROP TABLE IF EXISTS teachercrosssubject;

--
-- Drop table `answer`
--
DROP TABLE IF EXISTS answer;

--
-- Drop table `question`
--
DROP TABLE IF EXISTS question;

--
-- Drop table `test`
--
DROP TABLE IF EXISTS test;

--
-- Drop table `subject`
--
DROP TABLE IF EXISTS subject;

--
-- Drop table `student`
--
DROP TABLE IF EXISTS student;

--
-- Drop table `class`
--
DROP TABLE IF EXISTS class;

--
-- Drop table `teacher`
--
DROP TABLE IF EXISTS teacher;

--
-- Set default database
--
USE testao1145;

--
-- Create table `teacher`
--
CREATE TABLE teacher (
  Id int(11) NOT NULL AUTO_INCREMENT,
  FirstName varchar(255) DEFAULT NULL,
  LastName varchar(255) DEFAULT NULL,
  Login varchar(255) NOT NULL,
  Password varchar(255) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX UK_teacher_Id (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `class`
--
CREATE TABLE class (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Number int(11) DEFAULT NULL,
  Id_Teacher int(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE class
ADD CONSTRAINT FK_class_teacher_Id FOREIGN KEY (Id_Teacher)
REFERENCES teacher (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `student`
--
CREATE TABLE student (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FirstName varchar(255) DEFAULT NULL,
  LastName varchar(255) DEFAULT NULL,
  Age varchar(255) DEFAULT NULL,
  Login varchar(255) NOT NULL,
  Password varchar(255) NOT NULL,
  Id_Class int(11) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE student
ADD CONSTRAINT FK_student_class_Id FOREIGN KEY (Id_Class)
REFERENCES class (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `subject`
--
CREATE TABLE subject (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `test`
--
CREATE TABLE test (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) DEFAULT NULL,
  Id_Subject int(11) DEFAULT NULL,
  Id_Teacher int(11) DEFAULT NULL,
  CountQuestionTest int(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE test
ADD CONSTRAINT FK_test_subject_Id FOREIGN KEY (Id_Subject)
REFERENCES subject (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE test
ADD CONSTRAINT FK_test_teacher_Id FOREIGN KEY (Id_Teacher)
REFERENCES teacher (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `question`
--
CREATE TABLE question (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Name varchar(50) DEFAULT NULL,
  Id_Test int(11) DEFAULT NULL,
  Type int(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE question
ADD CONSTRAINT FK_question_test_Id FOREIGN KEY (Id_Test)
REFERENCES test (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `answer`
--
CREATE TABLE answer (
  Id int(11) NOT NULL AUTO_INCREMENT,
  text varchar(255) DEFAULT NULL,
  Id_Question int(11) DEFAULT NULL,
  RightAnswer tinyint(1) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE answer
ADD CONSTRAINT FK_answer_question_Id FOREIGN KEY (Id_Question)
REFERENCES question (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `teachercrosssubject`
--
CREATE TABLE teachercrosssubject (
  Id_Teacher int(11) NOT NULL,
  Id_Subject int(11) NOT NULL,
  PRIMARY KEY (Id_Teacher, Id_Subject)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE teachercrosssubject
ADD CONSTRAINT FK_teachercrosssubject_subject_Id FOREIGN KEY (Id_Subject)
REFERENCES subject (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE teachercrosssubject
ADD CONSTRAINT FK_teachercrosssubject_teacher_Id FOREIGN KEY (Id_Teacher)
REFERENCES teacher (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `mark`
--
CREATE TABLE mark (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Number int(11) DEFAULT NULL,
  CountQ int(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `studentanswer`
--
CREATE TABLE studentanswer (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Id_Student int(11) DEFAULT NULL,
  Id_Test int(11) DEFAULT NULL,
  DateTime datetime DEFAULT NULL,
  Id_Mark int(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE studentanswer
ADD CONSTRAINT FK_studentanswer_mark_Id FOREIGN KEY (Id_Mark)
REFERENCES mark (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE studentanswer
ADD CONSTRAINT FK_studentanswer_student_ID FOREIGN KEY (Id_Student)
REFERENCES student (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE studentanswer
ADD CONSTRAINT FK_studentanswer_test_Id FOREIGN KEY (Id_Test)
REFERENCES test (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `testcrossquestion`
--
CREATE TABLE testcrossquestion (
  Id_Student int(11) NOT NULL AUTO_INCREMENT,
  Id_Question int(11) NOT NULL,
  Id_Answer int(11) NOT NULL,
  PRIMARY KEY (Id_Student, Id_Question, Id_Answer)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE testcrossquestion
ADD CONSTRAINT FK_testcrossquestion_answer_Id FOREIGN KEY (Id_Answer)
REFERENCES answer (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE testcrossquestion
ADD CONSTRAINT FK_testcrossquestion_question_Id FOREIGN KEY (Id_Question)
REFERENCES question (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE testcrossquestion
ADD CONSTRAINT FK_testcrossquestion_studentanswer_Id FOREIGN KEY (Id_Student)
REFERENCES studentanswer (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table teacher
--
INSERT INTO teacher VALUES
(1, 'string', 'string', 'q', 'q');

-- 
-- Dumping data for table class
--
INSERT INTO class VALUES
(3, 1145, 1);

-- 
-- Dumping data for table subject
--
INSERT INTO subject VALUES
(1, 'математика'),
(2, 'string');

-- 
-- Dumping data for table student
--
INSERT INTO student VALUES
(6, 'string', 'string', 'string', 'w', 'w', 3);

-- 
-- Dumping data for table mark
--
INSERT INTO mark VALUES
(1, 5, 90),
(2, 4, 70),
(3, 3, 50),
(4, 2, 0);

-- 
-- Dumping data for table test
--
INSERT INTO test VALUES
(1, 'string string string string', 1, 1, 5);

-- 
-- Dumping data for table studentanswer
--
INSERT INTO studentanswer VALUES
(1, 6, 1, '2026-06-03 19:13:25', 4),
(2, 6, 1, '2026-06-03 19:16:56', 4);

-- 
-- Dumping data for table question
--
INSERT INTO question VALUES
(1, 'string', 1, NULL);

-- 
-- Dumping data for table answer
--
INSERT INTO answer VALUES
(1, 'string', 1, 1);

-- 
-- Dumping data for table testcrossquestion
--
INSERT INTO testcrossquestion VALUES
(1, 1, 1),
(2, 1, 1);

-- 
-- Dumping data for table teachercrosssubject
--
-- Table testao1145.teachercrosssubject does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;